spring.application.name=api-gateway
server.port=8081

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Gateway Configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Route Configuration for movies-service
spring.cloud.gateway.routes[0].id=movies-service
spring.cloud.gateway.routes[0].uri=lb://movies-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/movies/**
