spring.application.name=movies-service

# movies-service/src/main/resources/application.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/moviesmicroservice
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

# change temporarily (development only)
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# properties
springdoc.server-url=http://localhost:8080