# yaml
server:
  port: 8084

spring:
  application:
    name: user-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/booking-realm

  datasource:
    url: jdbc:postgresql://localhost:5432/microusers
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

aws:
  accessKeyId: fake-key
  secretAccessKey: fake-secret
  region: us-east-1
  s3:
    bucket-name: test-bucket

#aws:
#  accessKeyId: ${AWS_ACCESS_KEY_ID}
#  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
#  region: us-east-1
#  s3:
#    bucket-name: ${AWS_S3_BUCKET_NAME}

