package movies.moviesservice.Mappers.MovieMapper;

import movies.moviesservice.dtos.MovieDTO;
import movies.moviesservice.entity.Movie;
import movies.moviesservice.entity.language.Language;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Named;
import org.mapstruct.NullValuePropertyMappingStrategy;

import java.util.Set;
import java.util.stream.Collectors;

@Mapper(componentModel = "spring",
        nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
public interface MovieMapper {

    /**
     * Converts a Movie entity to a MovieDTO.
     * Only maps fields that exist in both entity and DTO.
     *
     * @param movie the entity to convert
     * @return the converted DTO
     */
    @Mapping(target = "languages", source = "languages", qualifiedByName = "languagesToStringSet")
    MovieDTO toDTO(Movie movie);

    /**
     * Converts a MovieDTO to a Movie entity.
     * Maps DTO fields to entity, id will be generated by JPA.
     *
     * @param dto the DTO to convert
     * @return the converted entity
     */
    @Mapping(target = "languages", ignore = true)
    Movie toEntity(MovieDTO dto);

    /**
     * Helper used by MapStruct to convert entity languages to simple String names.
     */
    @Named("languagesToStringSet")
    default Set<String> languagesToStringSet(Set<Language> languages) {
        if (languages == null) return null;
        return languages.stream()
                .map(Language::getName)
                .collect(Collectors.toSet());
    }

}
